# -*- coding: utf-8 -*-
"""Salinan dari 2702360712_Dimas Ardiansyah P_LAB 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L8uxkUlQbfwVWjWS6rHDcSjSK7YhtXen
"""

import time
print(time.ctime())

import numpy as np
np.array
x = np.array([1, 4, 3])
x

import numpy as np
np.array
y = np.array([[1, 4, 3], [9, 2, 7]])
y

def my_adder(a, b, c):
     """
     function to sum the 3 numbers
     input: 3 numbers a, b, c
     output:
     date:
     """

     # this is the summation
     out = a + b + c

     return out

my_adder(1,2,3)

def my_thermo_stat(temp, desired_temp):
  if temp < desired_temp - 5:
    status = 'Heat'
  elif temp > desired_temp + 5:
    status = 'AC'
  else:
      status = 'off'
  return status

status = my_thermo_stat(65,75)
print(status)

status = my_thermo_stat(76,65)
print(status)

status = my_thermo_stat(65,63)
print(status)

x = 3
if x>1 and x<2:
  y = 2
elif x>2 and x<4:
  y = 4
else:
  y = 0
print(y)

x = 3
if 1<x<2:
  y = 2
elif 2<x<4:
  y = 4
else:
  y = 0
print(y)